spring:
  profiles:
    active: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    maxLifetime: 1765000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
    maximumPoolSize: 15 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
    #type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    #schema: import.sql
  mvc:
    view:
      prefix: /WEB-INF/html/
      suffix: .html

mybatis:
   #*Mapper.java可以随便放，只要和mapper.xml对应上就行
   mapper-locations: classpath*:mybatis/sqlmap/*.xml
   type-aliases-package: com.example.entity
   #config: mybatis-config.xml

#这个插件是mybatis的分页查询
pagehelper:
   helperDialect: mysql
   reasonable: true
   supportMethodsArguments: true
   params: count=countSql