server:
  context-path: /demo
  port: 8081

logging:
#日志配置部分
   file: /home/logs/demo.log
   level:
       root: info
       com.*.mapper: debug

spring:
   datasource:
       url: jdbc:mysql://localhost:3306/dbdemo
       username: root
       password: 1234